mysql:
  build: .
  dockerfile: Dockerfile-MySQL
  environment:
    MYSQL_ROOT_PASSWORD: root         #rootユーザ用のパスワード
    MYSQL_USER: user1                 #作業ユーザ名
    MYSQL_PASSWORD: user1password     #作業ユーザ用のパスワード
    MYSQL_DATABASE: development_db    #作成するDB名
    TZ: "Asia/Tokyo"
  ports:
    - 3306:3306
  volumes:
    - ./db:/var/lib/mysql